* April 19, 2011
1. pacman --sync --refresh
2. pacman --sync --pacman
3. [root@shilohsystem ~]# pacman --sync pacman
   resolving dependencies...
   looking for inter-conflicts...
   
  Targets (18): linux-api-headers-3.3-1  glibc-2.15-10  xz-5.0.3-2  
   libarchive-3.0.4-1  run-parts-4.2.1-1  
   ca-certificates-20120212-1  libssh2-1.4.0-1  curl-7.25.0-1  
   pth-2.0.7-4  libksba-1.2.0-1  libassuan-2.0.3-1  
   pinentry-0.8.1-3  libsasl-2.1.23-9  libldap-2.4.30-1  
   dirmngr-1.1.0-4  gnupg-2.0.19-1  gpgme-1.3.1-4  pacman-4.0.3-1  
   
  Total Download Size:    12.76 MB
  Total Installed Size:   59.88 MB
   
  Proceed with installation? [Y/n] 
4. (18/18) checking for file conflicts                 [###################] 100%
  error: failed to commit transaction (conflicting files)
  glibc: /usr/bin/tzselect exists in filesystem
  glibc: /usr/sbin/zdump exists in filesystem
  glibc: /usr/sbin/zic exists in filesystem
  Errors occurred, no packages were upgraded.
5. [root@shilohsystem ~]# mv --interactive /etc/profile.d/locale.sh /tmp
  [root@shilohsystem ~]# pacman --sync initscripts
  :: The following packages should be upgraded first :
   pacman  
  :: Do you want to cancel the current operation
  :: and upgrade these packages now? [Y/n] n
   
  resolving dependencies...
  looking for inter-conflicts...
  :: kmod conflicts with module-init-tools. Remove module-init-tools? [Y/n] 
   
  Remove (1): module-init-tools-3.11.1-2  
   
  Total Removed Size:   0.73 MB
   
  Targets (6): kmod-7-2  pciutils-3.1.9-1  usbutils-005-1  udev-182-1  
   iproute2-3.2.0-3  initscripts-2012.03.2-1  
   
  Total Download Size:    0.00 MB
  Total Installed Size:   5.17 MB
   
  Proceed with installation? [Y/n] 
  checking package integrity...
  (6/6) checking for file conflicts                   [###################] 100%
  (1/1) removing module-init-tools                    [###################] 100%
  (1/6) installing kmod                               [###################] 100%
  (2/6) installing pciutils                           [###################] 100%
  Optional dependencies for pciutils
   sh: required by update-pciids
  (3/6) installing usbutils                           [###################] 100%
  Optional dependencies for usbutils
   python2: for lsusb.py usage
   coreutils: for lsusb.py usage
   wget: for update-usbids.sh usage
  (4/6) upgrading udev                                [###################] 100%
  udev changes:
 * Kernel 2.6.32 or newer is now required.
 * OSS emulation modules are not loaded by default, add to rc.conf if needed.
 * Arch specific cd symlinks are now no longer created.
 * cd and net persistent rules will no longer be autogenerated,
   see <https://wiki.archlinux.org/index.php/Udev> for details.
 * Errors are now logged (possibly to the console) by default.
 * Arch's custom blacklisting logic has been removed. MOD_AUTOLOAD and
   blacklisting in MODULES no longer works.
   See 'man modprobe.conf' for a replacement to blacklisting.
   To disable a module mod1 on the kernel command line, use
     mod1.disable=1
   or
     modprobe.blacklist=mod1
 * The following modules are no longer unconditionally loaded:
     pcspkr irtty-sir analog lp ppdev ide-generic
   Add them to MODULES in rc.conf if you need them.
 * Blacklisting of framebuffer devices has moved from /etc/modprobe.d to
   /lib/modprobe.d. Any customizations shoud be done to the file in /etc, as it
   takes precedence.
 * kbd and rtc devices are no longer world readable.
 * rtc is no longer in the audio group and fb devices are no longer in
   the video group, as permissions and ownership of fb devices are controlled
   by X.
 * We now use upstream rules for assigning devices to the 'disk', 'optical',
   'scanner' and 'video' groups. Beware of any changes.
 * We no longer create symlinks from /dev/<dev> to /dev/<dev>0.
 * For security reasons, we no longer add devices to the 'storage' group. Use
   udisks and friends, or add custom rules to /etc/udev.d/rules/, if you want
   this functionality back.
 * We no longer create the static nodes on install needed for an initrd-less
   boot where devtmpfs is not mounted by the kernel, this only affects fresh
   installs.
 * devtmpfs support is now a hard requirement. Users of the official Arch
   kernels have this enabled.
 * udev-compat has been removed, and should be uninstalled.
 * Framebuffers are no longer blacklisted by default.
 * binaries moved from /sbin to /usr/bin
 * if your kernel does not provide /dev/loop-control, you need to manually
   load the 'loop' module before using losetup
  (5/6) installing iproute2                           [###################] 100%
  Optional dependencies for iproute2
   linux-atm: ATM support
  (6/6) upgrading initscripts                         [###################] 100%
  warning: extracting /etc/inittab as /etc/inittab.pacnew
  warning: /etc/rc.conf installed as /etc/rc.conf.pacnew
  warning: extracting /etc/rc.sysinit as /etc/rc.sysinit.pacnew
  Blacklisting of modules is no longer supported in rc.conf,
  please add blacklist entries to /etc/modprobe.d/ instead.
  VERBOSE= in rc.conf no longer has any effect.
  Please append 'quiet' to your kernel command line.
  If using non-bash-compatible shell, please set LANG in /etc/locale.conf,
  as LOCALE in /etc/rc.conf no longer works.
  New optional dependencies for initscripts
   net-tools: legacy network support
6. [root@shilohsystem etc]# pacman --sync filesystem --force
  :: The following packages should be upgraded first :
   pacman  
  :: Do you want to cancel the current operation
  :: and upgrade these packages now? [Y/n] n
   
  resolving dependencies...
  looking for inter-conflicts...
   
  Targets (2): iana-etc-2.30-2  filesystem-2012.2-4  
   
  Total Download Size:    0.20 MB
  Total Installed Size:   0.97 MB
   
  Proceed with installation? [Y/n] 
  :: Retrieving packages from core...
   iana-etc-2.30-2-any...   198.2K  507.7K/s 00:00:00 [###################] 100%
   filesystem-2012.2-4...     4.0K   83.0M/s 00:00:00 [###################] 100%
  checking package integrity...
  (1/2) installing iana-etc                           [###################] 100%
  (2/2) upgrading filesystem                          [###################] 100%
  warning: /etc/hosts installed as /etc/hosts.pacnew
  warning: /etc/gshadow installed as /etc/gshadow.pacnew
  warning: /etc/shadow installed as /etc/shadow.pacnew
